### ISSUE TITLE
Get rid of # in URLs

### ISSUE THREAD

**Issue by dmnd** [jasonLaster/abuses#23]
I think this must exist because we're supporting browsers that don't have the pushState API... but we use lots of other features that won't work on those browsers. So let's require pushState and have a cleaner URL.

**Comment by michielkoning** [comment]
I've tried to fix that, but it doesn't work properly:
The homepage still works and you can navigate without the #:
https://deploy-preview-24--police-accountability.netlify.app/

But deeplinking to a video generates a 404:
https://deploy-preview-24--police-accountability.netlify.app/ESAl1OK5V8Y

Netlify hosts static sites and can't find ESAl1OK5V8Y.html in de root, only index.html. To fix this we need SSR for that, a framework that generates html files when building.

**Comment by dmnd** [comment]
Oh, in that case we could do this: https://docs.netlify.com/routing/redirects/rewrites-proxies/#history-pushstate-and-single-page-apps

**Comment by michielkoning** [comment]
Cool! Wasn't aware of that feature.

**Comment by michielkoning** [comment]
It works :). I've updated the PR:
https://github.com/jasonLaster/abuses/pull/24

**Comment by dmnd** [comment]
closing this in favour of your #24
