### ISSUE TITLE
Support default airtable values

### ISSUE THREAD

**Issue by jasonLaster** [jasonLaster/abuses#40]
It might be nice to enforce the invariant that fields that have a value are strings, and those that do not have a value are null. So here we'd need to have || null on the youtube and text too.

Furthermore, it's probably nice to trim the strings coming in from airtable in case a field is just whitespace. So I'd do this:

```js
function extractField(s) {
  return s?.trim() ?? null
}  
```

**Comment by grinnellian** [comment]
Nod. I think yesterday we were assuming those values were always present maybe? Bad assumption but it let us move fast :-)
