### ISSUE TITLE
Fix meta info displayed when shared on social media

### ISSUE THREAD

**Issue by dmnd** [jasonLaster/abuses#62]
From @ramezn: A couple social media issues: When sharing it on twitter or FB:

1. There's no default image any more.
2. The description still says "200+ Videos"
3. The URL shown in the FB share attachment is "police-accountability.netlify.app"

![image](https://user-images.githubusercontent.com/4427/86043390-8821c380-b9fd-11ea-96d6-ba33db163972.png)

**Comment by michielkoning** [comment]
We will need [Vue meta](https://www.npmjs.com/package/vue-meta) to fix this. You can set metadata per view.

**Comment by michielkoning** [comment]
This is fixed.
